services:
  app:
    build: .
    image: sweetme:latest
    container_name: sweetme-app
    ports:
      - "21001:21002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /Users/goodgid/.oci/oci_api_key.pem:/root/.oci/oci_api_key.pem:ro
      - ./oci_docker_config:/root/.oci/config:ro
    restart: unless-stopped
